#!/bin/bash

cd ~/
mkdir firexapps
mkdir .firexdata
cd ~/firexapps
mkdir minecraft-server
cd ~/firexapps/minecarft-server
wget https://www.dropbox.com/s/m7hkxgn48eoqfuk/server.jar
clear
wget https://raw.githubusercontent.com/Firexlator/minecraft_server/main/eula.txt
clear
wget https://raw.githubusercontent.com/Firexlator/minecraft_server/main/start
clear
cd ~/.firexdata
mkdir minecraft-server
cd ~/.firexdata/minecraft-server
wget https://github.com/Firexlator/minecraft_server/raw/main/logo.png
clear
cd ~/
mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Name=Minecraft server
Comment=Start minecraft server
Exec=~/firexapps/minecraft-server/start
Icon=~/.firexdata/minecraft-server/logo.png
Terminal=true
Type=Application
Categories=Utility;
StartupNotify=true" > ~/.local/share/applications/minecraft-server.desktop
cp -f ~/.local/share/applications/minecraft-server.desktop ~/Desktop
clear
echo Dowwnload finished!

