#!/bin/bash

function error {
  echo -e "\e[91m$1\e[39m"
  exit 1
}

cd "$HOME"

#ensure non-root
if [[ "$(id -u)" == 0 ]]; then
  error "Minecraft server is not designed to be installed as root! Please try again as a regular user."
fi

#ensure debian
command -v apt >/dev/null || error "apt: command not found. Most likely this system is not running Debian."

sudo apt update || error "The command 'sudo apt update' failed. Before Minecraft server will work, you must fix your apt package-management system."

#install dependencies
dependencies='yad curl wget aria2 lsb-release apt-utils imagemagick bc librsvg2-bin locales shellcheck git wmctrl xdotool x11-utils rsync default-jre'

if ! dpkg -s $dependencies &>/dev/null ;then
  sudo apt install $dependencies -y -f --no-install-recommends
fi
echo

#remove annoying "YAD icon browser" launcher
sudo rm -f /usr/share/applications/yad-icon-browser.desktop

#download pi-apps if folder missing
DIRECTORY="$(readlink -f "$(dirname "$0")")"
if [ -z "$DIRECTORY" ] || [ "$DIRECTORY" == "$HOME" ] || [ "$DIRECTORY" == bash ];then
  DIRECTORY="$HOME/firexapps"
fi
downloaded=0 #track if pi-apps was downloaded this time

#Re-download pi-apps folder if local git repo is over 1 months out of date
if [ -d "$DIRECTORY" ];then
  #first compare local git repo's last-commit-time with the current system time (Unix epoch time format)
  current_git_date="$(cd "$DIRECTORY"; git show -s --format=%ct)"
  current_local_date="$(date +%s)"
  if [ -z "$current_git_date" ] || [ "$current_local_date" -gt $(($current_git_date + 30*60*60*24)) ];then
    
    #if local git repo's last-commit-time is 3 months older than current system time, now compare the local git repo's last-commit-time with the online repo's modification time to avoid false positives.
    #This two-tiered approach prevents unnecessary GitHub API calls and speeds up script's execution for normal usage.
    
    command -v curl >/dev/null || sudo apt install -y curl
    upstream_git_date="$(curl https://api.github.com/repos/Firexlator/minecraft_server/commit/main 2>&1 | grep '"date":' | tail -n 1 | sed 's/"date"://g' | xargs date +%s -d 2>/dev/null)"
    
    if [[ "$upstream_git_date" =~ ^[0-9]+$ ]] && ([ -z "$current_git_date" ] || [ "$upstream_git_date" -gt $(($current_git_date + 30*60*60*24)) ]);then
      rm -rf ~/pi-apps-forced-update
      
      echo "Reinstalling Minecarft server..."
      downloaded=1
      output="$(git clone --depth 1 https://github.com/Firexlator/minecraft_server ~/minecraft-server-forced-update 2>&1)"
      if [ $? != 0 ] || [ ! -d "$DIRECTORY" ];then
        error "Minecraft server download failed!\ngit clone output was: $output"
      fi
      cp -af "${DIRECTORY}/data" ~/minecraft-server-forced-update
      cp -af "${DIRECTORY}/apps" ~/minecraft-server-forced-update
      rm -rf "$DIRECTORY"
      mv -f ~/minecraft-server-forced-update "$DIRECTORY"
    fi
  fi
  
#if pi-apps folder does not exist, download it
elif [ ! -d "$DIRECTORY" ];then
  echo "Downloading Minecraft server..."
  downloaded=1
  wget https://www.dropbox.com/s/m7hkxgn48eoqfuk/server.jar
  output="$(git clone --depth 1 https://github.com/Firexlator/minecarft_server "$DIRECTORY" 2>&1)"
  if [ $? != 0 ] || [ ! -d "$DIRECTORY" ];then
    error "Minecarft server download failed!\ngit clone output was: $output"
  fi
fi

#Past this point, DIRECTORY variable populated with valid pi-apps directory

#if ChromeOS, install lxterminal
if command -v garcon-terminal-handler >/dev/null ;then
  echo "In order to install apps on ChromeOS, a working terminal emulator is required.
Installing lxterminal in 10 seconds... (press Ctrl+C to cancel)"
  sleep 10
  sudo apt install -yf lxterminal || error "Failed to install lxterminal on ChromeOS!"
fi

#menu button
if [ ! -f ~/.local/share/applications/minecraft-server.desktop ];then
  echo "Creating menu button..."
fi
mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Name=Minecraft server
Comment=Start minecraft server
Exec=${DIRECTORY}/start.sh
Icon=${DIRECTORY}/logo.png
Terminal=true
Type=Application
Categories=Utility;
StartupNotify=true" > ~/.local/share/applications/minecraft-server.desktop

#copy menu button to Desktop
cp -f ~/.local/share/applications/minecraft-server.desktop ~/Desktop



m

#pi-apps terminal command
if [ ! -f /usr/local/bin/pi-apps ] || ! cat /usr/local/bin/minecraft-server | grep -q "${DIRECTORY}/start" ;then
  echo "#!/bin/bash
${DIRECTORY}/gui"' "$@"' | sudo tee /usr/local/bin/minecraft-server >/dev/null
  sudo chmod +x /usr/local/bin/minecraft-server
fi



if [ $downloaded == 1 ];then
  echo "Installation complete. Minecraft server can be launched from the start menu or by running the command 'minecraft-server'."
else
  echo -e "Please note that Minecraft server has NOT been freshly downloaded, because $DIRECTORY already exists."
fi
