#!/bin/bash
echo Starting download of your minecraft server
cd ~/
mkdir .firexapps
cd ~/.firexapps
mkdir mcserver
cd ~/.firexapps/mcserver
wget https://www.dropbox.com/s/m7hkxgn48eoqfuk/server.jar
clear
wget https://www.dropbox.com/s/c2iipmev6dqetvy/eula.txt
clear
wget https://www.dropbox.com/s/33u3o3ttn3rv61k/logo.png
clear
wget https://www.dropbox.com/s/fdyogtz7lqvjqsk/start.sh
clear
wget https://www.dropbox.com/s/neno8tu0vxn57lx/startgui.sh
clear
cd ~/Desktop
wget https://www.dropbox.com/s/5y41jcoerekyadz/Server
clear
echo Download finished!


